# Generated by Django 2.1 on 2018-12-07 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QMLove', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profileImage',
            field=models.ImageField(null=True, upload_to='profile_images/'),
        ),
    ]
