# Generated by Django 2.1 on 2018-12-07 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('QMLove', '0003_auto_20181207_1725'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='profileImage',
            new_name='image',
        ),
    ]
