# Generated by Django 2.1 on 2018-12-07 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QMLove', '0004_auto_20181207_1729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='profile_images'),
        ),
    ]
